//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ScheduleIdField;
        
        private int TrainIdField;
        
        private int DepartureStationIdField;
        
        private int ArrivalStationIdField;
        
        private System.DateTime DepartureTimeField;
        
        private System.DateTime ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNameField;
        
        private int AvailableSeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TrainId {
            get {
                return this.TrainIdField;
            }
            set {
                if ((this.TrainIdField.Equals(value) != true)) {
                    this.TrainIdField = value;
                    this.RaisePropertyChanged("TrainId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DepartureStationId {
            get {
                return this.DepartureStationIdField;
            }
            set {
                if ((this.DepartureStationIdField.Equals(value) != true)) {
                    this.DepartureStationIdField = value;
                    this.RaisePropertyChanged("DepartureStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ArrivalStationId {
            get {
                return this.ArrivalStationIdField;
            }
            set {
                if ((this.ArrivalStationIdField.Equals(value) != true)) {
                    this.ArrivalStationIdField = value;
                    this.RaisePropertyChanged("ArrivalStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((this.DepartureTimeField.Equals(value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((this.ArrivalTimeField.Equals(value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TrainName {
            get {
                return this.TrainNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNameField, value) != true)) {
                    this.TrainNameField = value;
                    this.RaisePropertyChanged("TrainName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AvailableSeats {
            get {
                return this.AvailableSeatsField;
            }
            set {
                if ((this.AvailableSeatsField.Equals(value) != true)) {
                    this.AvailableSeatsField = value;
                    this.RaisePropertyChanged("AvailableSeats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StationId {
            get {
                return this.StationIdField;
            }
            set {
                if ((this.StationIdField.Equals(value) != true)) {
                    this.StationIdField = value;
                    this.RaisePropertyChanged("StationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BookingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private System.Nullable<int> BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ClientServiceSoap")]
    public interface ClientServiceSoap {
        
        // CODEGEN: Generating message contract since element name SearchTrainsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchTrains", ReplyAction="*")]
        BookingWebApplication.ServiceReference1.SearchTrainsResponse SearchTrains(BookingWebApplication.ServiceReference1.SearchTrainsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchTrains", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.SearchTrainsResponse> SearchTrainsAsync(BookingWebApplication.ServiceReference1.SearchTrainsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStations", ReplyAction="*")]
        BookingWebApplication.ServiceReference1.GetStationsResponse GetStations(BookingWebApplication.ServiceReference1.GetStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStations", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.GetStationsResponse> GetStationsAsync(BookingWebApplication.ServiceReference1.GetStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableSeats", ReplyAction="*")]
        int GetAvailableSeats(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableSeats", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAvailableSeatsAsync(int scheduleId);
        
        // CODEGEN: Generating message contract since element name nic from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBooking", ReplyAction="*")]
        BookingWebApplication.ServiceReference1.AddBookingResponse AddBooking(BookingWebApplication.ServiceReference1.AddBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.AddBookingResponse> AddBookingAsync(BookingWebApplication.ServiceReference1.AddBookingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTrainsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTrains", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.SearchTrainsRequestBody Body;
        
        public SearchTrainsRequest() {
        }
        
        public SearchTrainsRequest(BookingWebApplication.ServiceReference1.SearchTrainsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchTrainsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int departureStationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arrivalStationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        public SearchTrainsRequestBody() {
        }
        
        public SearchTrainsRequestBody(int departureStationId, int arrivalStationId, System.DateTime date) {
            this.departureStationId = departureStationId;
            this.arrivalStationId = arrivalStationId;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTrainsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTrainsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.SearchTrainsResponseBody Body;
        
        public SearchTrainsResponse() {
        }
        
        public SearchTrainsResponse(BookingWebApplication.ServiceReference1.SearchTrainsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchTrainsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookingWebApplication.ServiceReference1.Schedule[] SearchTrainsResult;
        
        public SearchTrainsResponseBody() {
        }
        
        public SearchTrainsResponseBody(BookingWebApplication.ServiceReference1.Schedule[] SearchTrainsResult) {
            this.SearchTrainsResult = SearchTrainsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStations", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.GetStationsRequestBody Body;
        
        public GetStationsRequest() {
        }
        
        public GetStationsRequest(BookingWebApplication.ServiceReference1.GetStationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStationsRequestBody {
        
        public GetStationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.GetStationsResponseBody Body;
        
        public GetStationsResponse() {
        }
        
        public GetStationsResponse(BookingWebApplication.ServiceReference1.GetStationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookingWebApplication.ServiceReference1.Station[] GetStationsResult;
        
        public GetStationsResponseBody() {
        }
        
        public GetStationsResponseBody(BookingWebApplication.ServiceReference1.Station[] GetStationsResult) {
            this.GetStationsResult = GetStationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBooking", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.AddBookingRequestBody Body;
        
        public AddBookingRequest() {
        }
        
        public AddBookingRequest(BookingWebApplication.ServiceReference1.AddBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int scheduleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nic;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int seatCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passengerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactInfo;
        
        public AddBookingRequestBody() {
        }
        
        public AddBookingRequestBody(int scheduleId, string nic, int seatCount, string passengerName, string contactInfo) {
            this.scheduleId = scheduleId;
            this.nic = nic;
            this.seatCount = seatCount;
            this.passengerName = passengerName;
            this.contactInfo = contactInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference1.AddBookingResponseBody Body;
        
        public AddBookingResponse() {
        }
        
        public AddBookingResponse(BookingWebApplication.ServiceReference1.AddBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookingWebApplication.ServiceReference1.BookingResponse AddBookingResult;
        
        public AddBookingResponseBody() {
        }
        
        public AddBookingResponseBody(BookingWebApplication.ServiceReference1.BookingResponse AddBookingResult) {
            this.AddBookingResult = AddBookingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientServiceSoapChannel : BookingWebApplication.ServiceReference1.ClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceSoapClient : System.ServiceModel.ClientBase<BookingWebApplication.ServiceReference1.ClientServiceSoap>, BookingWebApplication.ServiceReference1.ClientServiceSoap {
        
        public ClientServiceSoapClient() {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference1.SearchTrainsResponse BookingWebApplication.ServiceReference1.ClientServiceSoap.SearchTrains(BookingWebApplication.ServiceReference1.SearchTrainsRequest request) {
            return base.Channel.SearchTrains(request);
        }
        
        public BookingWebApplication.ServiceReference1.Schedule[] SearchTrains(int departureStationId, int arrivalStationId, System.DateTime date) {
            BookingWebApplication.ServiceReference1.SearchTrainsRequest inValue = new BookingWebApplication.ServiceReference1.SearchTrainsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.SearchTrainsRequestBody();
            inValue.Body.departureStationId = departureStationId;
            inValue.Body.arrivalStationId = arrivalStationId;
            inValue.Body.date = date;
            BookingWebApplication.ServiceReference1.SearchTrainsResponse retVal = ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).SearchTrains(inValue);
            return retVal.Body.SearchTrainsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.SearchTrainsResponse> BookingWebApplication.ServiceReference1.ClientServiceSoap.SearchTrainsAsync(BookingWebApplication.ServiceReference1.SearchTrainsRequest request) {
            return base.Channel.SearchTrainsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.SearchTrainsResponse> SearchTrainsAsync(int departureStationId, int arrivalStationId, System.DateTime date) {
            BookingWebApplication.ServiceReference1.SearchTrainsRequest inValue = new BookingWebApplication.ServiceReference1.SearchTrainsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.SearchTrainsRequestBody();
            inValue.Body.departureStationId = departureStationId;
            inValue.Body.arrivalStationId = arrivalStationId;
            inValue.Body.date = date;
            return ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).SearchTrainsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference1.GetStationsResponse BookingWebApplication.ServiceReference1.ClientServiceSoap.GetStations(BookingWebApplication.ServiceReference1.GetStationsRequest request) {
            return base.Channel.GetStations(request);
        }
        
        public BookingWebApplication.ServiceReference1.Station[] GetStations() {
            BookingWebApplication.ServiceReference1.GetStationsRequest inValue = new BookingWebApplication.ServiceReference1.GetStationsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.GetStationsRequestBody();
            BookingWebApplication.ServiceReference1.GetStationsResponse retVal = ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).GetStations(inValue);
            return retVal.Body.GetStationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.GetStationsResponse> BookingWebApplication.ServiceReference1.ClientServiceSoap.GetStationsAsync(BookingWebApplication.ServiceReference1.GetStationsRequest request) {
            return base.Channel.GetStationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.GetStationsResponse> GetStationsAsync() {
            BookingWebApplication.ServiceReference1.GetStationsRequest inValue = new BookingWebApplication.ServiceReference1.GetStationsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.GetStationsRequestBody();
            return ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).GetStationsAsync(inValue);
        }
        
        public int GetAvailableSeats(int scheduleId) {
            return base.Channel.GetAvailableSeats(scheduleId);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableSeatsAsync(int scheduleId) {
            return base.Channel.GetAvailableSeatsAsync(scheduleId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference1.AddBookingResponse BookingWebApplication.ServiceReference1.ClientServiceSoap.AddBooking(BookingWebApplication.ServiceReference1.AddBookingRequest request) {
            return base.Channel.AddBooking(request);
        }
        
        public BookingWebApplication.ServiceReference1.BookingResponse AddBooking(int scheduleId, string nic, int seatCount, string passengerName, string contactInfo) {
            BookingWebApplication.ServiceReference1.AddBookingRequest inValue = new BookingWebApplication.ServiceReference1.AddBookingRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.AddBookingRequestBody();
            inValue.Body.scheduleId = scheduleId;
            inValue.Body.nic = nic;
            inValue.Body.seatCount = seatCount;
            inValue.Body.passengerName = passengerName;
            inValue.Body.contactInfo = contactInfo;
            BookingWebApplication.ServiceReference1.AddBookingResponse retVal = ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).AddBooking(inValue);
            return retVal.Body.AddBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.AddBookingResponse> BookingWebApplication.ServiceReference1.ClientServiceSoap.AddBookingAsync(BookingWebApplication.ServiceReference1.AddBookingRequest request) {
            return base.Channel.AddBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference1.AddBookingResponse> AddBookingAsync(int scheduleId, string nic, int seatCount, string passengerName, string contactInfo) {
            BookingWebApplication.ServiceReference1.AddBookingRequest inValue = new BookingWebApplication.ServiceReference1.AddBookingRequest();
            inValue.Body = new BookingWebApplication.ServiceReference1.AddBookingRequestBody();
            inValue.Body.scheduleId = scheduleId;
            inValue.Body.nic = nic;
            inValue.Body.seatCount = seatCount;
            inValue.Body.passengerName = passengerName;
            inValue.Body.contactInfo = contactInfo;
            return ((BookingWebApplication.ServiceReference1.ClientServiceSoap)(this)).AddBookingAsync(inValue);
        }
    }
}
