//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWebApplication.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookingIdField;
        
        private int ScheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NICField;
        
        private int SeatCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassengerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NIC {
            get {
                return this.NICField;
            }
            set {
                if ((object.ReferenceEquals(this.NICField, value) != true)) {
                    this.NICField = value;
                    this.RaisePropertyChanged("NIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SeatCount {
            get {
                return this.SeatCountField;
            }
            set {
                if ((this.SeatCountField.Equals(value) != true)) {
                    this.SeatCountField = value;
                    this.RaisePropertyChanged("SeatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PassengerName {
            get {
                return this.PassengerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PassengerNameField, value) != true)) {
                    this.PassengerNameField = value;
                    this.RaisePropertyChanged("PassengerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactInfo {
            get {
                return this.ContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfoField, value) != true)) {
                    this.ContactInfoField = value;
                    this.RaisePropertyChanged("ContactInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTrain", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.AddTrainResponse AddTrain(BookingWebApplication.ServiceReference2.AddTrainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTrain", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddTrainResponse> AddTrainAsync(BookingWebApplication.ServiceReference2.AddTrainRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTrain", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.UpdateTrainResponse UpdateTrain(BookingWebApplication.ServiceReference2.UpdateTrainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTrain", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateTrainResponse> UpdateTrainAsync(BookingWebApplication.ServiceReference2.UpdateTrainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTrain", ReplyAction="*")]
        void DeleteTrain(int trainId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTrain", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteTrainAsync(int trainId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableSeats", ReplyAction="*")]
        int GetAvailableSeats(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableSeats", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAvailableSeatsAsync(int scheduleId);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStation", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.AddStationResponse AddStation(BookingWebApplication.ServiceReference2.AddStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStation", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddStationResponse> AddStationAsync(BookingWebApplication.ServiceReference2.AddStationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStation", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.UpdateStationResponse UpdateStation(BookingWebApplication.ServiceReference2.UpdateStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStation", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateStationResponse> UpdateStationAsync(BookingWebApplication.ServiceReference2.UpdateStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStation", ReplyAction="*")]
        void DeleteStation(int stationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStation", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteStationAsync(int stationId);
        
        // CODEGEN: Generating message contract since element name AddScheduleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSchedule", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.AddScheduleResponse AddSchedule(BookingWebApplication.ServiceReference2.AddScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddScheduleResponse> AddScheduleAsync(BookingWebApplication.ServiceReference2.AddScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedule", ReplyAction="*")]
        void UpdateSchedule(int scheduleId, int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateScheduleAsync(int scheduleId, int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchedule", ReplyAction="*")]
        void DeleteSchedule(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteScheduleAsync(int scheduleId);
        
        // CODEGEN: Generating message contract since element name GetBookingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookings", ReplyAction="*")]
        BookingWebApplication.ServiceReference2.GetBookingsResponse GetBookings(BookingWebApplication.ServiceReference2.GetBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.GetBookingsResponse> GetBookingsAsync(BookingWebApplication.ServiceReference2.GetBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBooking", ReplyAction="*")]
        void DeleteBooking(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBooking", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteBookingAsync(int bookingId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrain", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddTrainRequestBody Body;
        
        public AddTrainRequest() {
        }
        
        public AddTrainRequest(BookingWebApplication.ServiceReference2.AddTrainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTrainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int seatCount;
        
        public AddTrainRequestBody() {
        }
        
        public AddTrainRequestBody(string name, int seatCount) {
            this.name = name;
            this.seatCount = seatCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTrainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTrainResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddTrainResponseBody Body;
        
        public AddTrainResponse() {
        }
        
        public AddTrainResponse(BookingWebApplication.ServiceReference2.AddTrainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTrainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTrainResult;
        
        public AddTrainResponseBody() {
        }
        
        public AddTrainResponseBody(string AddTrainResult) {
            this.AddTrainResult = AddTrainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrain", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.UpdateTrainRequestBody Body;
        
        public UpdateTrainRequest() {
        }
        
        public UpdateTrainRequest(BookingWebApplication.ServiceReference2.UpdateTrainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTrainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trainId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int seatCount;
        
        public UpdateTrainRequestBody() {
        }
        
        public UpdateTrainRequestBody(int trainId, string name, int seatCount) {
            this.trainId = trainId;
            this.name = name;
            this.seatCount = seatCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTrainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTrainResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.UpdateTrainResponseBody Body;
        
        public UpdateTrainResponse() {
        }
        
        public UpdateTrainResponse(BookingWebApplication.ServiceReference2.UpdateTrainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTrainResponseBody {
        
        public UpdateTrainResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStation", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddStationRequestBody Body;
        
        public AddStationRequest() {
        }
        
        public AddStationRequest(BookingWebApplication.ServiceReference2.AddStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AddStationRequestBody() {
        }
        
        public AddStationRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddStationResponseBody Body;
        
        public AddStationResponse() {
        }
        
        public AddStationResponse(BookingWebApplication.ServiceReference2.AddStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddStationResult;
        
        public AddStationResponseBody() {
        }
        
        public AddStationResponseBody(string AddStationResult) {
            this.AddStationResult = AddStationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStation", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.UpdateStationRequestBody Body;
        
        public UpdateStationRequest() {
        }
        
        public UpdateStationRequest(BookingWebApplication.ServiceReference2.UpdateStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int stationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public UpdateStationRequestBody() {
        }
        
        public UpdateStationRequestBody(int stationId, string name) {
            this.stationId = stationId;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.UpdateStationResponseBody Body;
        
        public UpdateStationResponse() {
        }
        
        public UpdateStationResponse(BookingWebApplication.ServiceReference2.UpdateStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStationResponseBody {
        
        public UpdateStationResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSchedule", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddScheduleRequestBody Body;
        
        public AddScheduleRequest() {
        }
        
        public AddScheduleRequest(BookingWebApplication.ServiceReference2.AddScheduleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddScheduleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trainId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int departureStationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int arrivalStationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime departureTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime arrivalTime;
        
        public AddScheduleRequestBody() {
        }
        
        public AddScheduleRequestBody(int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime) {
            this.trainId = trainId;
            this.departureStationId = departureStationId;
            this.arrivalStationId = arrivalStationId;
            this.departureTime = departureTime;
            this.arrivalTime = arrivalTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddScheduleResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.AddScheduleResponseBody Body;
        
        public AddScheduleResponse() {
        }
        
        public AddScheduleResponse(BookingWebApplication.ServiceReference2.AddScheduleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddScheduleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddScheduleResult;
        
        public AddScheduleResponseBody() {
        }
        
        public AddScheduleResponseBody(string AddScheduleResult) {
            this.AddScheduleResult = AddScheduleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookings", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.GetBookingsRequestBody Body;
        
        public GetBookingsRequest() {
        }
        
        public GetBookingsRequest(BookingWebApplication.ServiceReference2.GetBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBookingsRequestBody {
        
        public GetBookingsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookingWebApplication.ServiceReference2.GetBookingsResponseBody Body;
        
        public GetBookingsResponse() {
        }
        
        public GetBookingsResponse(BookingWebApplication.ServiceReference2.GetBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookingWebApplication.ServiceReference2.Booking[] GetBookingsResult;
        
        public GetBookingsResponseBody() {
        }
        
        public GetBookingsResponseBody(BookingWebApplication.ServiceReference2.Booking[] GetBookingsResult) {
            this.GetBookingsResult = GetBookingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : BookingWebApplication.ServiceReference2.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<BookingWebApplication.ServiceReference2.AdminServiceSoap>, BookingWebApplication.ServiceReference2.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.AddTrainResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.AddTrain(BookingWebApplication.ServiceReference2.AddTrainRequest request) {
            return base.Channel.AddTrain(request);
        }
        
        public string AddTrain(string name, int seatCount) {
            BookingWebApplication.ServiceReference2.AddTrainRequest inValue = new BookingWebApplication.ServiceReference2.AddTrainRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddTrainRequestBody();
            inValue.Body.name = name;
            inValue.Body.seatCount = seatCount;
            BookingWebApplication.ServiceReference2.AddTrainResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddTrain(inValue);
            return retVal.Body.AddTrainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddTrainResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.AddTrainAsync(BookingWebApplication.ServiceReference2.AddTrainRequest request) {
            return base.Channel.AddTrainAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddTrainResponse> AddTrainAsync(string name, int seatCount) {
            BookingWebApplication.ServiceReference2.AddTrainRequest inValue = new BookingWebApplication.ServiceReference2.AddTrainRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddTrainRequestBody();
            inValue.Body.name = name;
            inValue.Body.seatCount = seatCount;
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddTrainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.UpdateTrainResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.UpdateTrain(BookingWebApplication.ServiceReference2.UpdateTrainRequest request) {
            return base.Channel.UpdateTrain(request);
        }
        
        public void UpdateTrain(int trainId, string name, int seatCount) {
            BookingWebApplication.ServiceReference2.UpdateTrainRequest inValue = new BookingWebApplication.ServiceReference2.UpdateTrainRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.UpdateTrainRequestBody();
            inValue.Body.trainId = trainId;
            inValue.Body.name = name;
            inValue.Body.seatCount = seatCount;
            BookingWebApplication.ServiceReference2.UpdateTrainResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).UpdateTrain(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateTrainResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.UpdateTrainAsync(BookingWebApplication.ServiceReference2.UpdateTrainRequest request) {
            return base.Channel.UpdateTrainAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateTrainResponse> UpdateTrainAsync(int trainId, string name, int seatCount) {
            BookingWebApplication.ServiceReference2.UpdateTrainRequest inValue = new BookingWebApplication.ServiceReference2.UpdateTrainRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.UpdateTrainRequestBody();
            inValue.Body.trainId = trainId;
            inValue.Body.name = name;
            inValue.Body.seatCount = seatCount;
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).UpdateTrainAsync(inValue);
        }
        
        public void DeleteTrain(int trainId) {
            base.Channel.DeleteTrain(trainId);
        }
        
        public System.Threading.Tasks.Task DeleteTrainAsync(int trainId) {
            return base.Channel.DeleteTrainAsync(trainId);
        }
        
        public int GetAvailableSeats(int scheduleId) {
            return base.Channel.GetAvailableSeats(scheduleId);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableSeatsAsync(int scheduleId) {
            return base.Channel.GetAvailableSeatsAsync(scheduleId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.AddStationResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.AddStation(BookingWebApplication.ServiceReference2.AddStationRequest request) {
            return base.Channel.AddStation(request);
        }
        
        public string AddStation(string name) {
            BookingWebApplication.ServiceReference2.AddStationRequest inValue = new BookingWebApplication.ServiceReference2.AddStationRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddStationRequestBody();
            inValue.Body.name = name;
            BookingWebApplication.ServiceReference2.AddStationResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddStation(inValue);
            return retVal.Body.AddStationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddStationResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.AddStationAsync(BookingWebApplication.ServiceReference2.AddStationRequest request) {
            return base.Channel.AddStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddStationResponse> AddStationAsync(string name) {
            BookingWebApplication.ServiceReference2.AddStationRequest inValue = new BookingWebApplication.ServiceReference2.AddStationRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddStationRequestBody();
            inValue.Body.name = name;
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddStationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.UpdateStationResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.UpdateStation(BookingWebApplication.ServiceReference2.UpdateStationRequest request) {
            return base.Channel.UpdateStation(request);
        }
        
        public void UpdateStation(int stationId, string name) {
            BookingWebApplication.ServiceReference2.UpdateStationRequest inValue = new BookingWebApplication.ServiceReference2.UpdateStationRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.UpdateStationRequestBody();
            inValue.Body.stationId = stationId;
            inValue.Body.name = name;
            BookingWebApplication.ServiceReference2.UpdateStationResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).UpdateStation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateStationResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.UpdateStationAsync(BookingWebApplication.ServiceReference2.UpdateStationRequest request) {
            return base.Channel.UpdateStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.UpdateStationResponse> UpdateStationAsync(int stationId, string name) {
            BookingWebApplication.ServiceReference2.UpdateStationRequest inValue = new BookingWebApplication.ServiceReference2.UpdateStationRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.UpdateStationRequestBody();
            inValue.Body.stationId = stationId;
            inValue.Body.name = name;
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).UpdateStationAsync(inValue);
        }
        
        public void DeleteStation(int stationId) {
            base.Channel.DeleteStation(stationId);
        }
        
        public System.Threading.Tasks.Task DeleteStationAsync(int stationId) {
            return base.Channel.DeleteStationAsync(stationId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.AddScheduleResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.AddSchedule(BookingWebApplication.ServiceReference2.AddScheduleRequest request) {
            return base.Channel.AddSchedule(request);
        }
        
        public string AddSchedule(int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime) {
            BookingWebApplication.ServiceReference2.AddScheduleRequest inValue = new BookingWebApplication.ServiceReference2.AddScheduleRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddScheduleRequestBody();
            inValue.Body.trainId = trainId;
            inValue.Body.departureStationId = departureStationId;
            inValue.Body.arrivalStationId = arrivalStationId;
            inValue.Body.departureTime = departureTime;
            inValue.Body.arrivalTime = arrivalTime;
            BookingWebApplication.ServiceReference2.AddScheduleResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddSchedule(inValue);
            return retVal.Body.AddScheduleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddScheduleResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.AddScheduleAsync(BookingWebApplication.ServiceReference2.AddScheduleRequest request) {
            return base.Channel.AddScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.AddScheduleResponse> AddScheduleAsync(int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime) {
            BookingWebApplication.ServiceReference2.AddScheduleRequest inValue = new BookingWebApplication.ServiceReference2.AddScheduleRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.AddScheduleRequestBody();
            inValue.Body.trainId = trainId;
            inValue.Body.departureStationId = departureStationId;
            inValue.Body.arrivalStationId = arrivalStationId;
            inValue.Body.departureTime = departureTime;
            inValue.Body.arrivalTime = arrivalTime;
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).AddScheduleAsync(inValue);
        }
        
        public void UpdateSchedule(int scheduleId, int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime) {
            base.Channel.UpdateSchedule(scheduleId, trainId, departureStationId, arrivalStationId, departureTime, arrivalTime);
        }
        
        public System.Threading.Tasks.Task UpdateScheduleAsync(int scheduleId, int trainId, int departureStationId, int arrivalStationId, System.DateTime departureTime, System.DateTime arrivalTime) {
            return base.Channel.UpdateScheduleAsync(scheduleId, trainId, departureStationId, arrivalStationId, departureTime, arrivalTime);
        }
        
        public void DeleteSchedule(int scheduleId) {
            base.Channel.DeleteSchedule(scheduleId);
        }
        
        public System.Threading.Tasks.Task DeleteScheduleAsync(int scheduleId) {
            return base.Channel.DeleteScheduleAsync(scheduleId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingWebApplication.ServiceReference2.GetBookingsResponse BookingWebApplication.ServiceReference2.AdminServiceSoap.GetBookings(BookingWebApplication.ServiceReference2.GetBookingsRequest request) {
            return base.Channel.GetBookings(request);
        }
        
        public BookingWebApplication.ServiceReference2.Booking[] GetBookings() {
            BookingWebApplication.ServiceReference2.GetBookingsRequest inValue = new BookingWebApplication.ServiceReference2.GetBookingsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.GetBookingsRequestBody();
            BookingWebApplication.ServiceReference2.GetBookingsResponse retVal = ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).GetBookings(inValue);
            return retVal.Body.GetBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.GetBookingsResponse> BookingWebApplication.ServiceReference2.AdminServiceSoap.GetBookingsAsync(BookingWebApplication.ServiceReference2.GetBookingsRequest request) {
            return base.Channel.GetBookingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingWebApplication.ServiceReference2.GetBookingsResponse> GetBookingsAsync() {
            BookingWebApplication.ServiceReference2.GetBookingsRequest inValue = new BookingWebApplication.ServiceReference2.GetBookingsRequest();
            inValue.Body = new BookingWebApplication.ServiceReference2.GetBookingsRequestBody();
            return ((BookingWebApplication.ServiceReference2.AdminServiceSoap)(this)).GetBookingsAsync(inValue);
        }
        
        public void DeleteBooking(int bookingId) {
            base.Channel.DeleteBooking(bookingId);
        }
        
        public System.Threading.Tasks.Task DeleteBookingAsync(int bookingId) {
            return base.Channel.DeleteBookingAsync(bookingId);
        }
    }
}
